name: Terraform CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:


env:
  TF_VAR_tenancy_ocid: ${{ secrets.TENANCY_OCID }}
  TF_VAR_user_ocid: ${{ secrets.USER_OCID }}
  TF_VAR_fingerprint: ${{ secrets.FINGERPRINT }}
  TF_VAR_private_key: ${{ secrets.PRIVATE_KEY }}
  TF_VAR_region: ${{ secrets.REGION }}

  AWS_ACCESS_KEY_ID: ${{ secrets.OCI_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.OCI_SECRET_KEY }}

  TF_VERSION: 1.6.6

jobs:

  plan:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Create OCI private key
        run: |
                  echo "${{ secrets.PRIVATEKEY }}" | base64 -d > oci_api_key.pem
                    chmod 600 oci_api_key.pem
      - name: Debug private key
        run: |
                   echo "----- FILE CONTENT START -----"
                   head -5 oci_api_key.pem
                      echo "----- FILE CONTENT END -----"
      - name : Read a variable 
        run: echo "my tenancy id is ${{secrets.TENANCY_OCID}}"
        
      - name : Read a variable 
        run: echo "my tenancy id is ${{ secrets.USER_OCID }}"
        
      - name : Read a variable 
        run: echo "my tenancy id is ${{ secrets.FINGERPRINT }}"
        
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan


  apply:
    needs: plan
    runs-on: ubuntu-latest

    environment:
      name: apply-approval

    steps:
      - uses: actions/checkout@v4

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
